### ISSUE TITLE
蓝图冲突

### ISSUE THREAD

**Issue by renvip** [zkqiang/job-web-demo#3]
C:\Users\Admin\Envs\first_env\Scripts\python.exe -m flask run
 * Serving Flask app "manage.py"
 * Environment: development
 * Debug mode: off
Traceback (most recent call last):
  File "d:\program files\python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\flask\__main__.py", line 15, in <module>
    main(as_module=True)
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\flask\cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\flask\cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\flask\cli.py", line 305, in __init__
    self._load_unlocked()
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\flask\cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\flask\cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "D:\Users\Desktop\job-web-demo-master\manage.py", line 3, in <module>
    app = create_app('development')
  File "D:\Users\Desktop\job-web-demo-master\job_web\app.py", line 51, in create_app
    register_extensions(app)
  File "D:\Users\Desktop\job-web-demo-master\job_web\app.py", line 21, in register_extensions
    share.init_app(app)
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\flask_share\__init__.py", line 27, in init_app
    app.register_blueprint(blueprint)
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\flask\app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Users\Admin\Envs\first_env\lib\site-packages\flask\app.py", line 1160, in register_blueprint
    % (blueprint, self.blueprints[blueprint.name], blueprint.name)
AssertionError: A name collision occurred between blueprints <flask.blueprints.Blueprint object at 0x000001683C074EB8> and <flask.blueprints.Blueprint object at 0x000001683C074E48>. Both share the same name "share". Blueprints that are created on the fly need unique names.
请问如何解决？

**Comment by curriculum123** [comment]
将app.py中第20行中Share(app)中的app去掉，或者将21行“share=init_app(app)”注释掉，然后运行即可

**Comment by zkqiang** [comment]
@curriculum123 感谢，已修复
