### ISSUE TITLE
sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1055 (42000): 

### ISSUE THREAD

**Issue by simon-Hero** [zkqiang/job-web-demo#4]
sqlalchemy.exc.ProgrammingError
sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'job_web.job.created_at' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
[SQL: SELECT job.created_at AS job_created_at, job.updated_at AS job_updated_at, job.id AS job_id, job.name AS job_name, job.salary_min AS job_salary_min, job.salary_max AS job_salary_max, job.company_id AS job_company_id, job.description AS job_description, job.treatment AS job_treatment, job.exp AS job_exp, job.education AS job_education, job.city AS job_city, job.tags AS job_tags, job.is_enable AS job_is_enable 
FROM job GROUP BY job.company_id ORDER BY job.updated_at DESC 
 LIMIT %(param_1)s]
[parameters: {'param_1': 12}]
(Background on this error at: http://sqlalche.me/e/f405)

Traceback (most recent call last)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\sqlalchemy\engine\base.py", line 1246, in _execute_context
cursor, statement, parameters, context
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
cursor.execute(statement, parameters)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\mysql\connector\cursor.py", line 551, in execute
self._handle_result(self._connection.cmd_query(stmt))
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\mysql\connector\connection.py", line 490, in cmd_query
result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\mysql\connector\connection.py", line 395, in _handle_result
raise errors.get_exception(packet)
The above exception was the direct cause of the following exception:
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\flask\app.py", line 2463, in __call__
return self.wsgi_app(environ, start_response)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\flask\app.py", line 2449, in wsgi_app
response = self.handle_exception(e)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\flask\app.py", line 1866, in handle_exception
reraise(exc_type, exc_value, tb)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\flask\app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\flask\app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "E:\CTF_misc\杂铺\job-web-demo-master\job_web\handlers\front.py", line 25, in index
return render_template('index.html', active='index', jobs=jobs, companies=companies)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\flask\templating.py", line 140, in render_template
ctx.app,
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\flask\templating.py", line 120, in _render
rv = template.render(context)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
return original_render(self, *args, **kwargs)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\jinja2\environment.py", line 1008, in render
return self.environment.handle_exception(exc_info, True)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
reraise(exc_type, exc_value, tb)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\jinja2\_compat.py", line 37, in reraise
raise value.with_traceback(tb)
File "E:\CTF_misc\杂铺\job-web-demo-master\job_web\templates\index.html", line 2, in top-level template code
{% from "macros.html" import render_company, render_job %}
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\jinja2\environment.py", line 1005, in render
return concat(self.root_render_func(self.new_context(vars)))
File "E:\CTF_misc\杂铺\job-web-demo-master\job_web\templates\index.html", line 24, in root
{% for job in jobs %}
File "E:\CTF_misc\杂铺\job-web-demo-master\job_web\templates\base.html", line 129, in root
 
File "E:\CTF_misc\杂铺\job-web-demo-master\job_web\templates\index.html", line 49, in block_body
查看更多
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
return self._execute_and_instances(context)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
result = conn.execute(querycontext.statement, self._params)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
return meth(self, multiparams, params)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\sqlalchemy\engine\base.py", line 1101, in _execute_clauseelement
distilled_params,
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\sqlalchemy\engine\base.py", line 1250, in _execute_context
e, statement, parameters, cursor, context
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\sqlalchemy\engine\base.py", line 1476, in _handle_dbapi_exception
util.raise_from_cause(sqlalchemy_exception, exc_info)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
raise value.with_traceback(tb)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\sqlalchemy\engine\base.py", line 1246, in _execute_context
cursor, statement, parameters, context
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
cursor.execute(statement, parameters)
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\mysql\connector\cursor.py", line 551, in execute
self._handle_result(self._connection.cmd_query(stmt))
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\mysql\connector\connection.py", line 490, in cmd_query
result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
File "D:\Anaconda\python3_virtualenv\flaskApp\lib\site-packages\mysql\connector\connection.py", line 395, in _handle_result
raise errors.get_exception(packet)
sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'job_web.job.created_at' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
[SQL: SELECT job.created_at AS job_created_at, job.updated_at AS job_updated_at, job.id AS job_id, job.name AS job_name, job.salary_min AS job_salary_min, job.salary_max AS job_salary_max, job.company_id AS job_company_id, job.description AS job_description, job.treatment AS job_treatment, job.exp AS job_exp, job.education AS job_education, job.city AS job_city, job.tags AS job_tags, job.is_enable AS job_is_enable
FROM job GROUP BY job.company_id ORDER BY job.updated_at DESC
LIMIT %(param_1)s]
[parameters: {'param_1': 12}]
(Background on this error at: http://sqlalche.me/e/f405)
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by zhuligu** [comment]
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1049, "Unknown database 'job_web'")
